### ISSUE TITLE
Installation error on mysql-python

### ISSUE THREAD

**Issue by florianm** [DataShades/ckan-galleries#1]
During a source install of CKAN Galleries on Ubuntu 14.04 LTS, `python setup.py install` might run into problems when running `pip install mysql-python`: `EnvironmentError: mysql_config not found`

[Stackoverflow user amarillion](http://stackoverflow.com/users/3306/amarillion) suggests [installing a system package](http://stackoverflow.com/a/7475296): `sudo apt-get install libmariadbclient-dev` worked for me.

Suggestion: add this step to installation description?

**Comment by MrkGrgsn** [comment]
I'm not sure why mysql-python is required. @smotornyuk, @iaroslav13 , or @and-deryabkin can you comment?

**Comment by florianm** [comment]
Using datacats, the installation happens inside a docker container. There, I was able to satisfy the requirement for mysql_config only through `apt-get install libmysqlclient-dev`, while `libmariadbclient-dev` did not work. See [PR](https://github.com/datacats/datacats/pull/211).

**Comment by maxious** [comment]
MySQL is for the drupal auth plugin which AFAIK is identical to https://github.com/ckan/ckanext-drupal7/ so should not be be included in this repo.

**Comment by florianm** [comment]
datacats have included the dependency libmysqlclient-dev into their image, and normal CKAN installs get  away with apt-get installing it. Closing issue as it's only a cosmetic change.
